[build]
  command = "npm run build"
  publish = "dist/buscador-promocoes/browser"

[dev]
  command = "npm run start"
  port = 4200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
